### ISSUE TITLE
Automatically Populate the etymology with values entered in morphology

### ISSUE THREAD

**Issue by dadepo** [Yorubaname/yorubaname-dashboard#10]
As a user of the dashboard, I want that whatever breakdown i put into the morphology field should automatically appear in the etymology field:

For example https://www.dropbox.com/s/1943484jykzla21/Screenshot%202016-02-06%2014.43.18.png?dl=0

Further discussion still needs to be had on how to deal with morphology entries with multiple values.

**Comment by kolatubosun** [comment]
Is it live already?
 ------------


[image: www.kolatubosun.com]

*Kọ́lá Túbọ̀sún *
*website <http://www.kolatubosun.com>| wiki
<https://en.wikipedia.org/wiki/Kola_Tubosun> | linkedin
<https://www.linkedin.com/in/k%E1%BB%8D%CC%81la%CC%81-tu%CC%81b%E1%BB%8D%CC%80su%CC%81n-64a86912/>*
[image: https://]

**Comment by Zifah** [comment]
Yes

**Comment by kolatubosun** [comment]
It works!
 ------------


[image: www.kolatubosun.com]

*Kọ́lá Túbọ̀sún *
*website <http://www.kolatubosun.com>| wiki
<https://en.wikipedia.org/wiki/Kola_Tubosun> | linkedin
<https://www.linkedin.com/in/k%E1%BB%8D%CC%81la%CC%81-tu%CC%81b%E1%BB%8D%CC%80su%CC%81n-64a86912/>*
[image: https://]

**Comment by kolatubosun** [comment]
I like it, thank you.
PS: On a similar but slightly different note, can we have the "meaning"
field also populate from earlier entries from other names? For instance, a
morphology like "Ọlá" is usually "honour, wealth, notability", etc. I've
written this a million times for other entries. When it comes back for a
new name, can the field be already automatically populated? So all I need
to do is edit it if necessary. Same for all the others. So while I like the
current implementation when the morphemes are automatically populated, it
will be even better if already known meanings are pre-populated too.
 ------------


[image: www.kolatubosun.com]

*Kọ́lá Túbọ̀sún *
*website <http://www.kolatubosun.com>| wiki
<https://en.wikipedia.org/wiki/Kola_Tubosun> | linkedin
<https://www.linkedin.com/in/k%E1%BB%8D%CC%81la%CC%81-tu%CC%81b%E1%BB%8D%CC%80su%CC%81n-64a86912/>*
[image: https://]

**Comment by Zifah** [comment]
Sure it's possible.

But I'll ask you to create an issue and then rank the existing issues in
terms of priority. Think, if I could only resolve 5 to 10 additional issues
(which don't already have pull requests) within this phase of work, across
both website and dashboard, which ones would you select.

**Comment by kolatubosun** [comment]
I haven't checked the issues in years. Will take a look at the weekend when
I'm done with me current work.

**Comment by Zifah** [comment]
Sure. No hurry.

I'll continue with the current pull requests until then.
