### ISSUE TITLE
Lex-Bas Can't Update Entries

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-dashboard#13]
@dadepo This problem seems not to have gone away. I logged in with the username of a new lexicographer today and realised that entries aren't updating. If this can be fixed asap, that will be great. I suspect that this was what discouraged some of the earlier volunteers.
![screenshot 47](https://cloud.githubusercontent.com/assets/18510601/16870829/82e6570a-4a7b-11e6-8f57-63895708ed9e.png)

**Comment by dadepo** [comment]
The fix has been deployed for this issue Closing now
