### ISSUE TITLE
Can't Show All Feedbacks

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-dashboard#17]
Pardon me if this bug has been listed already. The problem is that I can't click on the "See all feedbacks" button and see all the feedbacks as should have been possible.
![screenshot 110](https://cloud.githubusercontent.com/assets/18510601/17277030/25a4cb7c-5731-11e6-8336-dcc051a9b9da.png)

**Comment by temiyemi** [comment]
@kolatubosun This seems to work fine when I tried it. It probably was just a one-off error when you experienced it.

**Comment by kolatubosun** [comment]
Yay, it works now. I'd experienced it more times than one before I filed it. Maybe it was fixed in the latest deployment?

**Comment by temiyemi** [comment]
Possibly. If it happens again, pls reopen it. Thanks.
